# Generated by Django 4.2.2 on 2026-03-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='next_available_session_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
