# Generated by Django 4.2.2 on 2026-03-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Coach', 'Coach'), ('Client', 'Client')], default=None, max_length=50, null=True),
        ),
    ]
