# Generated by Django 4.2.2 on 2026-05-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_alter_user_managers_alter_user_email'),
        ('userauths', '0002_user_user_type'),
    ]

    operations = [
    ]
