# Generated by Django 4.2.2 on 2026-05-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_merge_20260515_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
