# Generated by Django 4.2.2 on 2026-03-20 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dob',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
