# Generated by Django 4.2.2 on 2026-03-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('coach', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings', to='client.client'),
        ),
        migrations.AddField(
            model_name='service',
            name='available_coaches',
            field=models.ManyToManyField(blank=True, to='coach.coach'),
        ),
        migrations.AddField(
            model_name='session',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_client', to='client.client'),
        ),
        migrations.AddField(
            model_name='session',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_sessions', to='coach.coach'),
        ),
    ]
