# Generated by Django 4.2.2 on 2026-05-08 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_initial'),
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_sessions', to='coach.coach'),
        ),
    ]
