# Generated by Django 4.2.2 on 2026-05-15 07:46

from django.db import migrations, models
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=django_enum.fields.EnumCharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=16, null=True, verbose_name='Status'),
        ),
        migrations.AddConstraint(
            model_name='billing',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['paid', 'unpaid']), ('status__isnull', True), _connector='OR'), name='base_Billing_status_BillingStatusChoices'),
        ),
    ]
