# Generated by Django 4.2.30 on 2026-07-01 20:27

from django.db import migrations, models
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_sessionnote_resource_actionitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Event or Camp', 'verbose_name_plural': 'Events and Camps'},
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=django_enum.fields.EnumCharField(choices=[('event', 'Event'), ('camp', 'Camp')], default='event', max_length=16, verbose_name='Type'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['event', 'camp'])), name='base_Service_type_ServiceTypeChoices'),
        ),
    ]
