# Generated by Django 4.2.30 on 2026-07-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_service_options_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='max_tickets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
