# Generated by Codex on 2026-07-02

from django.db import migrations, models
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_billing_guest_email_service_max_tickets"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="billing",
            name="base_Billing_status_BillingStatusChoices",
        ),
        migrations.AlterField(
            model_name="billing",
            name="status",
            field=django_enum.fields.EnumCharField(
                blank=True,
                choices=[("paid", "Paid"), ("reserved", "Reserved"), ("unpaid", "Unpaid")],
                default="unpaid",
                max_length=16,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AddConstraint(
            model_name="billing",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ["paid", "reserved", "unpaid"]), ("status__isnull", True), _connector="OR"),
                name="base_Billing_status_BillingStatusChoices",
            ),
        ),
    ]
